import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

// wrap the project with Theme component
import { Theme } from "@radix-ui/themes";

import "@radix-ui/themes/styles.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={inter.className}>

      <Theme accentColor="blue" grayColor="olive" scaling="105%">
      {children}
      </Theme>

      </body>
    </html>
  )
}
